# Generated by Django 5.2.1 on 2026-08-12 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='账本名称')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='月度预算')),
                ('cover', models.CharField(blank=True, max_length=200, verbose_name='账本封面')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否归档')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认账本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '账本',
                'verbose_name_plural': '账本',
                'db_table': 'book',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='账户名称')),
                ('type', models.CharField(choices=[('cash', '现金'), ('wechat', '微信'), ('alipay', '支付宝'), ('bank_card', '银行卡'), ('credit_card', '信用卡')], default='cash', max_length=20, verbose_name='账户类型')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='初始余额')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='当前余额')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='bill.book', verbose_name='所属账本')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
                'db_table': 'account',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('type', models.CharField(choices=[('expense', '支出'), ('income', '收入')], default='expense', max_length=20, verbose_name='分类类型')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='分类图标')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='分类颜色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否系统默认')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='分类月度预算')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='bill.book', verbose_name='所属账本')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'category',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='标签颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='bill.book', verbose_name='所属账本')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tag',
                'ordering': ['-created_at'],
                'unique_together': {('book', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', '支出'), ('income', '收入'), ('transfer', '转账')], default='expense', max_length=20, verbose_name='账单类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('receipt_image', models.CharField(blank=True, max_length=500, verbose_name='凭证图片')),
                ('status', models.CharField(choices=[('normal', '正常'), ('deleted', '已删除')], default='normal', max_length=20, verbose_name='状态')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='是否周期账单')),
                ('recurring_type', models.CharField(choices=[('none', '无'), ('daily', '每日'), ('weekly', '每周'), ('monthly', '每月'), ('yearly', '每年')], default='none', max_length=20, verbose_name='周期类型')),
                ('recurring_next_at', models.DateTimeField(blank=True, null=True, verbose_name='下次自动入账时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_bills', to='bill.account', verbose_name='账户（转出）')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_bills', to='bill.account', verbose_name='转入账户（转账）')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='bill.book', verbose_name='所属账本')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='bill.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, related_name='bills', to='bill.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '账单',
                'verbose_name_plural': '账单',
                'db_table': 'bill',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
    ]
