# Generated by Django 5.2.1 on 2026-08-12 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发生时间'),
        ),
    ]
