# Generated by Django 5.2.1 on 2026-08-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_book_owner'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['book', 'status', 'occurred_at'], name='bill_book_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['book', 'type', 'occurred_at'], name='bill_book_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['category'], name='bill_category_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['account'], name='bill_account_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['to_account'], name='bill_to_account_idx'),
        ),
    ]
